name: ipatool-rs CI

on:
  workflow_dispatch:
  push:
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yml"

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install system deps
        run: |
          sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build lib
        run: |
          cargo build --no-default-features

      - name: Build bin
        run: |
          #FIXME: happens with auth info
          # Error: Keyring("Platform secure storage failure: DBus error: 
          # The name org.freedesktop.secrets was not provided by any .service files")
          #we need tests
          cargo run help
